# Generated by Django 4.2.5 on 2023-09-30 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120)),
                ('descripcion', models.CharField(max_length=500)),
                ('completado', models.BooleanField(default=False)),
            ],
        ),
    ]
